db.statistic.homepage:
    path:     /
    defaults: { _controller: DBStatisticBundle:Default:index }

db.statistic.data:
    path:     /data/{graphId}
    defaults: { _controller: DBStatisticBundle:Data:index }